version: '3'

services:
  mysql:
    image: mysql:8.3
    container_name: ${STAGE}.promise-api.mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./dockerdata/mysql.${STAGE}:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --performance-schema=OFF
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TIMEZONE}
    restart: always

  https:
    build:
      context: https
      args:
        - PORT=${PORT}
        - HTTPS=${HTTPS}
    image: promise-api:https
    container_name: promise-api.https
    ports:
      - 80:80
      - 443:443
    restart: always
