version: '3'

services:
  mysql:
    image: mysql:8.3
    container_name: promise-api.mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./dockerdata/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --performance-schema=OFF
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TIMEZONE}
    restart: always
