version: '3'

services:
  mysql:
    build:
      context: mysql
    image: promise-api:mysql
    container_name: promise-api.mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - promise-api_mysql
    volumes:
      - ./dockerdata/mysql.${STAGE}:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --performance-schema=OFF
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      USER: ${DB_USERNAME}
      PASSWORD: ${DB_PASSWORD}
      STAGE: ${STAGE}
      DATABASE: ${DB_NAME}
      TZ: ${DB_TIMEZONE}
    restart: always

  https:
    build:
      context: https
      args:
        - PORT=${PORT}
        - HTTPS=${HTTPS}
    image: promise-api:https
    container_name: promise-api.https
    networks:
      - promise-api_https
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  promise-api_mysql:
  promise-api_https:
