service: promise-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  architecture: arm64
  ecr:
    images:
      appimage:
        path: ./
        platform: linux/amd64
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: '*'
  vpc:
    securityGroupIds:
      - sg-0322225ba04d879fa
    subnetIds:
      - subnet-0428912e4d39d2947
      - subnet-075c29b5ae54675d0

functions:
  main:
    architecture: arm64
    image:
      name: appimage
      command:
        - dist/main.handler
      entryPoint:
        - /lambda-entrypoint.sh
    events:
      - httpApi:
          method: ANY
          path: /{any+}
