service: promise-api

frameworkVersion: '3'

plugins:
  - serverless-domain-manager
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
  domain:
    prod: api.promise-app.com
    dev: api.dev.promise-app.com
  customDomain:
    stage: ${self:provider.stage}
    domainName: ${self:custom.domain.${self:provider.stage}}
    certificateArn: arn:aws:acm:us-east-1:${aws:accountId}:certificate/bb2cf4ae-22a7-41c9-bfc4-98a983b88663

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_DEFAULT_REGION}
  stage: ${env:STAGE}
  httpApi:
    cors: true
  ecr:
    images:
      appimage:
        uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/${self:service}-${self:provider.stage}:appimage
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: '*'
        - Effect: Allow
          Action: s3:PutObject
          Resource: arn:aws:s3:::${env:AWS_S3_BUCKET_NAME}/*
  vpc:
    securityGroupIds:
      - sg-0322225ba04d879fa
    subnetIds:
      - subnet-0428912e4d39d2947
      - subnet-075c29b5ae54675d0
  websocketsApiName: ${self:provider.stage}-${self:service}-ws
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    SERVERLESS: true

    TZ: ${env:TZ}
    STAGE: ${self:provider.stage}
    NODE_ENV: ${env:NODE_ENV}
    NO_COLOR: ${env:NO_COLOR}

    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    INTHASH_KEY: ${env:INTHASH_KEY}

    JWT_ACCESS_EXPIRES_IN: ${env:JWT_ACCESS_EXPIRES_IN}
    JWT_REFRESH_EXPIRES_IN: ${env:JWT_REFRESH_EXPIRES_IN}

    DB_URL: ${env:DB_URL}

    AWS_S3_BUCKET_NAME: ${env:AWS_S3_BUCKET_NAME}

functions:
  main:
    timeout: 30
    memorySize: 1024
    image:
      name: appimage
      command:
        - dist/main.handler
      entryPoint:
        - /lambda-entrypoint.sh
    events:
      - http: ANY /
      - http: ANY /{proxy+}
      - websocket: $connect
      - websocket: $disconnect
      - websocket: $default
