services:
  mysql:
    image: mysql:8.3
    container_name: promise-api.mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - server
    volumes:
      - ./dockerdata/mysql.${STAGE}:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --performance-schema=OFF
      - --general-log=ON
      - --general-log-file=/var/lib/mysql/mysql.log
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
      DATABASE: ${DB_NAME}
      STAGE: ${STAGE}
      TZ: ${TZ}
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysql -uroot -p${DB_PASSWORD} ${DB_NAME}_${STAGE} -e "SELECT 1"']
      interval: 3s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    container_name: promise-api.redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - server
    volumes:
      - ./dockerdata/redis.${STAGE}:/data
    restart: always
    command:
      - --save 60 1
      - --requirepass ${REDIS_PASSWORD}

networks:
  server:
