services:
  https:
    image: promise-api:https
    container_name: promise-api.https
    pull_policy: never
    build:
      context: https
      args:
        - PORT=${PORT}
        - HTTPS=${HTTPS}
    networks:
      - https
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  https:
