version: '3'

services:
  promise.local:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8080
        - DOMAIN=api.promise-app.local
    image: promise-api:https
    container_name: promise-api.https
    ports:
      - '80:80'
      - '443:443'
