name: Deploy
run-name: deploy run name

on:
  push:
    branches:
      - development

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
      - run: |
          corepack yarn
          yarn set version berry
          yarn run build
      
      - name: AWS
      - run: |
          alias aws='docker run --rm -e AWS_DEFAULT_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY amazon/aws-cli'
          


