name: Deploy to AWS Lambda

on:
  push:
    branches:
      - develop
    paths:
      - 'package.json'
      - 'src/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      TZ: ${{ vars.TZ }}
      STAGE: dev
      NODE_ENV: development
      NO_COLOR: ${{ vars.NO_COLOR }}

      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_ACCESS_EXPIRES_IN: ${{ vars.JWT_ACCESS_EXPIRES_IN }}
      JWT_REFRESH_EXPIRES_IN: ${{ vars.JWT_REFRESH_EXPIRES_IN }}

      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ vars.DB_DATABASE }}
      DB_TIMEZONE: ${{ vars.DB_TIMEZONE }}

      REDIS_URL: ${{ vars.REDIS_URL }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: ${{ vars.AWS_S3_BUCKET_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to AWS ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.ecr.outputs.registry }}/promise-api-${{ env.STAGE }}:appimage
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          build-args: NOW=$(date +%Y-%m-%dT%H:%M:%S%z)

      - name: Install serverless framework
        run: npm install -g serverless serverless-domain-manager

      - name: Deploy to AWS Lambda
        run: serverless deploy --verbose --stage ${{ env.STAGE }}
