name: Deploy to AWS Lambda

on:
  push:
    branches:
      # - main
      - develop
      - deploy/*
    paths:
      - 'serverless.yml'
      - 'package.json'
      - 'src/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      TZ: ${{ vars.TZ }}
      STAGE: ${{ vars.STAGE }}
      NODE_ENV: ${{ vars.NODE_ENV }}
      NO_COLOR: ${{ vars.NO_COLOR }}

      JWT_SIGN_KEY: ${{ secrets.JWT_SIGN_KEY }}
      JWT_VERIFY_KEY: ${{ vars.JWT_VERIFY_KEY }}
      INTHASH_KEY: ${{ secrets.INTHASH_KEY }}
      SQIDS_KEY: ${{ secrets.SQIDS_KEY }}

      JWT_ACCESS_EXPIRES_IN: ${{ vars.JWT_ACCESS_EXPIRES_IN }}
      JWT_REFRESH_EXPIRES_IN: ${{ vars.JWT_REFRESH_EXPIRES_IN }}

      DB_URL: mysql://${{ vars.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_NAME }}_dev

      REDIS_HOST: ${{ vars.REDIS_HOST }}
      REDIS_PORT: ${{ vars.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: ${{ vars.AWS_S3_BUCKET_NAME }}

      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to AWS ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Github Environment Variables
        run: |
          echo "NOW=$(date +%Y-%m-%dT%H:%M:%S%z)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: docker/deploy.dockerfile
          tags: ${{ steps.ecr.outputs.registry }}/promise-api-${{ env.STAGE }}:appimage
          provenance: false
          build-args: |
            NOW=${{ env.NOW }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: Install Serverless Framework and Plugins
        run: npm install --global serverless@3 serverless-prune-plugin serverless-domain-manager

      - name: Deploy to AWS Lambda
        run: |
          serverless --version
          serverless deploy --verbose
