name: Pull Request

on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      DB_URL: mysql://${{ vars.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_NAME }}_${{ vars.STAGE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment and Run Tests
        uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: docker-compose.yml
          services: |
            mysql
            server
        env:
          TZ: ${{ vars.TZ }}
          PORT: ${{ vars.PORT }}
          STAGE: ${{ vars.STAGE }}
          NODE_ENV: ${{ vars.NODE_ENV }}

          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          INTHASH_KEY: ${{ secrets.INTHASH_KEY }}

          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_NAME: ${{ vars.DB_NAME }}

          DB_URL: ${{ env.DB_URL }}
